### ISSUE TITLE
Cross Domain Problem

### ISSUE THREAD

**Issue by CiccioCicc** [kahmali/meteor-restivus#139] opened 2015-10-01 14:03 UTC
Hi all,

I'm trying to make a get request, with ajax, to Restivus, but a problem occurred:

GET http://crossorigin.me/http://localhost:8081/api/publisher?topic=4JkWvxSZg8f…F,5wfn2n2DCh6KPP6xH;richiesta%20prenotazione%20Utente%20:4JkWvxSZg8fKCC7TF 500 (Internal Server Error)

this is my request:

get = function (type, idUtente, idCorsa, descrizione) {
    alert("inside get");
    var topic = {
        type: type,
        utente: idUtente,
        corsa: idCorsa,
        descrizione: descrizione
    };
    $.ajax({
        url: "http://crossorigin.me/http://localhost:8081/api/"+topic.type+"?topic="+topic.utente+","+topic.corsa+";"+topic.descrizione,
        dataType:'json',
        //crossOrigin: true,
        async: false,
        success: function (data) {
            if (data.status === "OK"){
                //alert("data= "+data);
                Notifications.new({ title: data, link: '/messages/1' });
            }
        }
    });
}

this is my code:

ApiV1 = new Restivus({
    prettyJson: true,
    defaultHeaders: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin' : "*"
    }
});

ApiV1.addRoute('subscriber', {
            get: function () {
            ..................
          }
      ....................
});

ApiV1.addRoute('publisher', {
  get: function () {
            ..................
          }
      ....................
});

Any advice?

Thanks a lot :)

**Comment by kahmali** [comment] 2015-10-01 16:11
This appears to be a duplicate of #125. Please check that thread for more info and continue the discussion there.

**Closed by kahmali** 2015-10-01 16:11 UTC
