### ISSUE TITLE
Cannot sign out via AJAX, but cURL works. Can't seem to figure this out

### ISSUE THREAD

**Issue by mhaagens** [kahmali/meteor-restivus#167] opened 2016-01-15 14:02 UTC
`axios.post('http://localhost:3000/api/logout', {
                data: null
            }, {
                headers: {
                    'Content-Type': 'application/json',
                    'X-Auth-Token': 'sTbX-toUJZ4Z9KOdt4nUVvlEcwIgtQhSr6D7QcLgpoY',
                    'X-User-Id': 'G7zsTxAuW3kpaZtgg'
                }
            })
            .then(function(response) {
                console.log(response);
            })
            .catch(function(response) {
                console.log(response);
            });`

Am I doing something wrong here? The headers are being passed in.

**Comment by kahmali** [comment] 2016-01-15 16:41
Duplicate of #166

**Closed by kahmali** 2016-01-15 16:41 UTC
Labels: duplicate
