### ISSUE TITLE
Getting returned only the raw HTML as the reponse

### ISSUE THREAD

**Issue by pihyper** [kahmali/meteor-restivus#164] opened 2016-01-05 08:06 UTC
Hi, i just came across this awesome package and started testing it. But everytime when i check the endpoint routes with CURL or POSTMAN chrome app, it just shows the html code rendered. I am confused and i have gone over the github documentation probably a 100 times already, im sure im doing everything right, but still no luck. 

My code  (written in server side)

```
Meteor.startup(function () {
    // Global API configuration
    var Api = new Restivus({
        useDefaultAuth: true,
        prettyJson: true,
        enableCors: false,
        version: 'v1',
        useClientRouter: false
    });

    Api.addCollection(Meteor.users, {
        excludedEndpoints: ['getAll', 'put'],
        routeOptions: {
            authRequired: true
        },
        endpoints: {
            post: {
                authRequired: false
            }
        }
    });

    Api.addRoute('operators/:id', {authRequired: false}, {
        get: function () {
            return Operators.findOne(this.urlParams.id);
        },
        delete: {
            action: function () {
                if (Operators.remove(this.urlParams.id)) {
                    return {status: 'success', data: {message: 'Article removed'}};
                }
                return {
                    statusCode: 404,
                    body: {status: 'fail', message: 'Article not found'}
                };
            }
        }
    });

})

```

Im using iron router package, but i also added the simple:json-routes package also, but issue persists. Even if i try to call http://localhost:3000/api/users (tried GET/POST etc), it rendering the HTML only, and i am aware that iron:router is intercepting these routes so if this is the case,how to overcome this. Perhaps i need to explicitly define these routes on iron router also?

Could you guide me please.

**Comment by kahmali** [comment] 2016-01-05 08:26
Hi @pihyper. Sorry you've been having trouble getting up and running. Can you provide a copy of a curl request and the response headers? Are you seeing any errors in the server console when you make the request? If so, please provide those as well. You'll get the raw html response whenever the request is not handled properly, but it can be one of many different things causing that. I need as much information as possible to try and help you. The code above looks fine at first glance, but I can't tell unless I see the request.

**Comment by pihyper** [comment] 2016-01-05 12:11
I'm developing in localhost.

I'm POSTing to url:  http://localhost:3000/api/users without any request headers and parameters, and without any arguments and im expecting a fail/error response. 

__Response Headers__
connection → keep-alive
content-type → text/html; charset=utf-8
date → Tue, 05 Jan 2016 12:05:28 GMT
transfer-encoding → chunked
vary → Accept-Encoding

**Comment by pihyper** [comment] 2016-01-05 12:26
No errors in server console also i had checked.

**Comment by kahmali** [comment] 2016-01-05 14:49
Can I see the actual curl request you're sending? I need to see if there's an error in the request. What happens when you send with the correct parameters? What happens when you try to access the `GET /operators/:id` route? Please try to provide as much information as possible, or reproduce this in a public sample repo that I can test with my own requests.

**Comment by scholp** [comment] 2016-01-06 02:33
Hi... I'm working on a project and I'm getting html response every time i hit and endpoint... even for /api/login

**Comment by pihyper** [comment] 2016-01-06 04:14
@kahmali , i found the issue and it was a silly mistake from my side. I think you failed to notice it too. ;)

i had my api version defined as v1, and all the time, i was calling the route wrongly as  localhost:3000/api/users, while it should have been localhost:3000/api/v1/users  (notice the "v1"). 
Now its giving me the expected response. :+1: 

@scholp : try the following code

```
@Api = new Restivus
  useDefaultAuth: true
  prettyJson: true

Api.addCollection Subscribers
```

In your code, i think the line "ApiV1.addCollection Subscribers" was what causing you the error as you had instantiated your restivus class in a variable called "Api" , and not "ApiV1".

**Comment by kahmali** [comment] 2016-01-06 04:40
Awesome @pihyper! I hate to say it, but I know when people are having this particular issue that it's something on their end. Restivus is being used successfully in thousands of apps. This error means either the API is not being accessed properly, or there is an error occurring that isn't being properly handled in the endpoint. In either case, the endpoint isn't being given a fair chance to respond. It's not something inherently wrong with Restivus, just the way it's being used. For anyone else having this issue, please just check the docs, your code, and your request. There's a 99% chance you're just doing something incorrectly. It's not that Restivus is broken :) It does what it's intended to do. The only reason it's not at 1.0 is because I really want to make it more modular so folks can build add-on packages without any issue (Astronomy-style), and that may require some major breaking changes I figured I would squeeze in a lot sooner.  

And hey! It's not my job to catch those small errors in your code, although I sure have fun trying :) You have to admit, that was pretty sneaky! :P I would have had a better chance if you gave me the curl request, which I would have converted to code if you didn't and had an easier time visually parsing. Finding errors in code is one thing. Finding errors in plain text with this font is an entirely different beast, and I'm way too spoiled with modern IDEs to catch anything like that. I wish I was that awesome. This is what it would have looked like with monospacing: `http://localhost:3000/api/users`. See, much easier on the eyes, right? At least, that's my story and I'm sticking to it :)

And yes @scholp, what @pihyper suggested should resolve your issue. I'm just shocked you weren't getting console errors on the server for `addCollection` not being a function on `ApiV1`, since it's value should have been `undefined`. Always get in the habit of checking for console errors when working with your REST API. 

I'm gonna go ahead and close this thread. Thanks for reporting the issue @pihyper, and even more for following up with your solution.

**Closed by kahmali** 2016-01-06 04:40 UTC

**Comment by scholp** [comment] 2016-01-06 12:44
@pihyper @kahmali yes... it was my silly mistake. I had not installed coffeescript so the coffee file wasn't being read by meteor... thanks anyways

**Comment by Bhanupriya1303** [comment] 2016-07-29 07:44
If bymistake someone has fetched by using wrong url, and  it shows the html code rendered then how to give the proper error message.
