### ISSUE TITLE
TypeError: first argument must be a string or Buffer

### ISSUE THREAD

**Issue by xanatas** [kahmali/meteor-restivus#72] opened 2015-05-18 17:09 UTC
I tried 

```javascript
return {
  statusCode: 404, 
  headers: {
    'Content-Type': 'text/plain', 
    'X-Custom-Header': 'custom value'
  },        
  body: {
    status: 'success', 
    data: {
      message: 'There is nothing here!'
    } 
  } 
};
```

i get

    TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (http.js:852:11)
    at ServerResponse.res.write (/Users/pscigala/.meteor/packages/webapp/.1.2.0.195w94w++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:110:17)
    at Route.Route._respond (packages/nimble:restivus/lib/route.coffee:209:30)
    at [object Object].Router.route.action (packages/nimble:restivus/lib/route.coffee:62:16)
    at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at packages/meteor/dynamics_nodejs.js:121:1

any ideas how to return a 404 properly? i tried statusCode: "404"

**Comment by kahmali** [comment] 2015-05-18 17:23
Sorry about that! There's an error in that example in the docs and I'm just in the middle of finals and haven't had time to fix it (I'll leave this issue open until I do). The problem is that you're setting the `Content-Type` to `text/plain`, but then returning JSON in the response body. I'm evil for doing that. If your goal is to return plain text, just change the `body` to a raw string. Otherwise, just remove the `Content-Type` header and it will fall back to the default, which is `application/json`.

**Comment by xanatas** [comment] 2015-05-18 17:40
Thanks that gave me a headache.. Thanks for the quick response.
Good luck with the finals.

**Comment by kahmali** [comment] 2015-05-18 18:10
No problem! Sorry for any frustration it caused! I fixed the title of the issue so hopefully it will be easier to find if someone else runs into the same problem. You're actually the 2nd person to report an issue directly related to this, and I dropped the ball closing the previous one without fixing the docs - #61. Shame on me. If I had a timeout chair, I'd be sitting in it right now.

**Comment by kahmali** [comment] 2015-05-21 07:55
Updated the [docs](https://github.com/kahmali/meteor-restivus#response-data). Thanks again for reporting this!

**Closed by kahmali** 2015-05-21 07:55 UTC
Labels: documentation, will accept pull request
