### ISSUE TITLE
Flow router support with restivus

### ISSUE THREAD

**Issue by reduxdj** [kahmali/meteor-restivus#130] opened 2015-08-23 17:05 UTC
Any idea if flow router, which seems like it's going to be the most popular router for react? Is switching restivus to  flow router a plan?

**Comment by voidale** [comment] 2015-08-27 13:55
+1

**Comment by voidale** [comment] 2015-08-27 14:06
@kahmali it seems there is a conflict with flow router? If you're logged in the server side route will not work, It loads client side files weird...

**Comment by kahmali** [comment] 2015-08-27 14:53
@reduxdj Absolutely not! And for good reason. :) Flow Router is my favorite client-side router, and I use it in my own projects; but it's just that, a [_client-side_ router](https://github.com/kadirahq/flow-router/issues/133). Restivus is a [_server-side_ router](https://kadira.io/academy/meteor-routing-guide/content/server-side-routing-rest). They are two completely separate concepts, and so the idea of Restivus "supporting" Flow Router is actually impossible. Even Arunoda built a separate package, Picker, for server-side routing, since Flow Router (wisely) doesn't support it. Restivus and Flow Router are both good at doing their jobs and staying out of the other's way. 

@voidale If for some reason you think that Restivus is interfering with Flow Router (I _strongly_ doubt it is, for the reasons Arunoda explained in those links above), please open a separate issue with detailed reproduction steps, or, even better, a sample repo demonstrating the issue. 

I'm going to go ahead and close this.  Thanks for asking the question @reduxdj!

**Closed by kahmali** 2015-08-27 14:53 UTC
Labels: question
