### ISSUE TITLE
Facebook auth with token

### ISSUE THREAD

**Issue by ganySA** [kahmali/meteor-restivus#37] opened 2015-04-23 05:59 UTC
Hi

I would like to authenticate using native device IOS token, i found a great post that seems to provide half the answer at this http://stackoverflow.com/questions/18118503/how-can-i-login-to-meteor-with-native-device-facebook. That would technically authenticate the user into the meteor stack, however my question is how would i go about using that to get a token for restivus? (/api/login)

Thanks

**Comment by kahmali** [comment] 2015-04-23 06:41
I don't know much about authenticating with Facebook, but as long as you're able to generate a token that's stored in a user document, you should be able to use the custom auth options to add this functionality.

I think this is a duplicate of Issue #7. Please check out the discussion there and see if the custom auth option in Restivus is sufficient (I don't see why it wouldn't be). I'm going to close this as a duplicate. You can continue any discussion over in the other thread, which I've left open since I do still intend to eventually add some native options for external auth (maybe just a custom auth add-on package).

**Closed** 2015-04-23 06:42 UTC
Labels: duplicate
